# Base de datos
spring.datasource.url=jdbc:postgresql://dpg-dahmpgss728c73cn01q0-a.ohio-postgres.render.com/donadoresyentidades_xnw8
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=donadoresyentidades_xnw8_user
spring.datasource.password=pycld6DoxgVTTzRvhmrYn3QE6Pt5a0rt
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Actuator y Métricas
management.datadog.metrics.export.enabled=${DATADOG_ENABLED:false}
management.datadog.metrics.export.api-key=${DATADOG_API_KEY:}
management.datadog.metrics.export.application-key=${DATADOG_APP_KEY:}
management.datadog.metrics.export.step=1m
management.datadog.metrics.export.uri=${DATADOG_URI:https://api.datadoghq.com}/
management.metrics.tags.modulo=donadoresYEntidades


# Microservicios
server.port=${PORT:8082}

url.logistica=https://logistica-7m62.onrender.com
url.donaciones=https://donaciones-b4cs.onrender.com
url.donadoresYEntidades=https://donadoresyentidades.onrender.com
url.incentivos=https://incentivos-cxk9.onrender.com


# Server
