# Base de datos
spring.datasource.url=jdbc:postgresql://dpg-d8is0758nd3s73dts7og-a.ohio-postgres.render.com:5432/donadoresyentidades
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=donadoresyentidades_user
spring.datasource.password=NYGwAMxyVCanybCTxTN19aWY11F3Tz1O
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Actuator y Métricas
management.datadog.metrics.export.uri=https://api.datadoghq.com
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.step=30s
management.datadog.metrics.export.api-key=6b4af422f0aae09dff0df439ab873c80
management.datadog.metrics.export.applicationKey=ddapp_wR3lFSs0Pk3wUEEMpabToXyU1sFF2s1wBR
management.metrics.tags.modulo=donadoresYEntidades

# Microservicios
INCENTIVOS_SERVICE_URL=http://localhost:8081
LOGISTICA_SERVICE_URL=http://localhost:8082
DONACIONES_SERVICE_URL=http://localhost:8083

# Server
server.port=${PORT:8080}